name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - dev
      - feature-8-plaid
      - master

jobs:
  
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
  
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          milliseconds: 1000
